#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"
#include "CImg.h"
#include "FreeImage.h"
//// end generated include

//#include <wx/filedlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
//#include <wx/colourdata.h>
//#include <wx/colordlg.h>
#include <wx/msgdlg.h>

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void m_wxPanel_update(wxUpdateUIEvent& event ) override;
		void m_b_load_click(wxCommandEvent& event ) override;
		void m_b_animate_click(wxCommandEvent& event ) override;
		void m_b_erode_click(wxCommandEvent& event ) override;
        void m_b_censor_click(wxCommandEvent& event ) override;
        void m_exif_panel_update(wxUpdateUIEvent& event) override;
        void Animate();
        void ToglleIsAnimating();
public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
        ~GUIMyFrame1()
        {
            if (image_freeimg) {
                FreeImage_Unload(image_freeimg);

            }
            FreeImage_DeInitialise();



        }
	//// end generated class members

    wxImage WX_Image;
    wxBitmap _animationFrames[60];
    FIBITMAP* image_freeimg;
    cimg_library::CImg<unsigned char> image_cimg;        // This will be the unchanged reference image
    cimg_library::CImg<unsigned char> image_cimg_process; // This will be the image to process
    std::vector<std::pair<std::string, std::string>> exif_info;
    bool isAnimating;



  void Repaint(wxDC& dc);
  void OnPaint(wxPaintEvent& event);
  void LoadFreeImage(const wxString& fileName);
  void LoadCImg(const wxString& fileName);

};

#endif // __GUIMyFrame1__
